---
title: "Work HappieR - Weekly sales report"
author: "Eline Krijkamp"
date: "6-6-2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown for the weekly sales 

This is the sales report generated at `r strftime(Sys.time(), "%H:%M %Z %d %B %Y")`.


###  R Markdown for the weekly sales 

```{r, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
source("../R/app0_library-setup.R") # Load the libraries
load("../output/sales_weekly.RData")
source("../functions/plot-weekly-sales_functions.R")
# Load the data from the csv files and store in the R environment
sales_summary   <- read.csv("../data/sales_summary.csv") 
```

## Sales Summary Data

### Table
Below is a table with the total number of units sold per widget.
```{r tables-sales_summary, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE}
knitr::kable(sales_summary, format = 'html', caption = 'Total units sold per product')
```

### Chart
Here is a chart with the same data.
```{r echo = FALSE, eval = TRUE, warning = FALSE, fig.height = 4, message = FALSE}
# Plot a bar chart of total sales per product.
ggplot(sales_summary, aes(x = widget, y = count / 1000000)) +
  geom_col(fill = "#3498db") +
  labs(x = "product", y = "units sold / million") +
  ggtitle("Total units sold")
```





## Overal data
### Best week for each country
```{r, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE}
sales_weekly_best <- sales_weekly %>%
  group_by(country_name, week_number) %>%
  summarise(count = sum(count)) %>%
  arrange(desc(count)) %>%
  slice(1)
```

```{r, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE}
knitr::kable(sales_weekly_best, format = 'html', caption = 'Best week for each county')
```

### Detailed graphs
```{r, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE}
country_value <- "USA"
PlotWeeklySalesPerCountry(country_value = "USA")  
PlotWeeklySalesPerCountry(country_value = "GBR")  
PlotWeeklySalesPerCountry(country_value = "FRA")  
PlotWeeklySalesPerCountry(country_value = "ZAF")  
``` 




